import { useState } from "react";
import { Globe, AlertTriangle, ChevronDown, ExternalLink, Info, CheckCircle2, BookOpen } from "lucide-react";

// ─── Static data ────────────────────────────────────────────────────────────

const CRITICAL_RULES = [
  {
    rule: "Passport-exact data",
    detail: "Personal data on Universitaly MUST match the passport exactly — including all middle names and surnames. Mismatches cause rejection.",
  },
  {
    rule: "One programme, one university",
    detail: "A student can pre-enrol on Universitaly for only ONE programme at ONE university. Choose carefully before submitting.",
  },
  {
    rule: "Conditional vs unconditional",
    detail: "Pre-enrolment is first validated conditionally. The visa requires UNCONDITIONAL validation — see the Validation section.",
  },
  {
    rule: "UNIBO issues NO admission letters for visa applications",
    detail: "Do not promise clients one. The validated Universitaly summary is the only document the Embassy accepts.",
    bologna: true,
  },
  {
    rule: "Auto-generated tax code is NOT the official Italian one",
    detail: "The codice fiscale generated by Universitaly is a placeholder. The real one is obtained separately from the Agenzia delle Entrate or an Italian embassy — before or after arrival.",
  },
];

const STEPS: { n: number; title: string; body: string; warning?: string; bologna?: boolean }[] = [
  {
    n: 1,
    title: "Register on Universitaly",
    body: "Go to www.universitaly.it → Registration. Click \"Credenziali Personali (Universitaly)\" → \"Registrati\". Complete the Registration form with personal data copied exactly from the passport → Save. An email link arrives → click it → choose a password. Back on the homepage → \"Pre-enroll now\" → log in → \"Pre-enrolment application\".",
  },
  {
    n: 2,
    title: "Start the application",
    body: "Click \"New pre-enrolment application\". The portal reminds you: one institution and one course only; course type is listed in Italian even for English programmes; to modify after submitting, contact the institution directly; to fix personal data, contact Technical Support with a passport copy.",
  },
  {
    n: 3,
    title: "STEP A — Personal data",
    body: "Enter: academic year, full name (including middle names), surname, birth date, gender, country and town/city of birth, current citizenship(s), official home address, telephone, email.\n\nItalian tax code field: fill only if you already have an official one — leave blank otherwise.",
    warning: "The tax code the system auto-generates here is NOT the official Italian codice fiscale.",
  },
  {
    n: 4,
    title: "STEP B — Passport, visa & course",
    body: "• Passport: number + expiry date; upload a face photo and the valid passport scan (pdf/jpeg/png, max 10 MB each).\n\n• Visa application: select the Country and the Embassy/Consulate where the visa will be requested. Reason for the visa: choose \"I want to enrol in a study course.\"\n\n• Course information:\n   — Institution Name: Università degli Studi di Bologna\n   — Course Type: Laurea (bachelor) / Laurea Magistrale a ciclo unico (single-cycle) / Laurea Magistrale (master's)\n   — Languages: select \"every languages\"\n   — Course Name: the degree programme\n   — Course Curriculum (if available): the curriculum\n\n• ID account at the chosen University: enter the @studio.unibo.it account. No account yet? Register on Studenti Online first.",
    bologna: true,
  },
  {
    n: 5,
    title: "STEP C — Qualifications",
    body: "Upload the qualification (high-school diploma or degree with transcript) and, if available, translation, proof of authenticity, and the Declaration of Value / CIMEA documents.\n\nIf you don't have everything yet, upload what you have — missing items can be added later (check with the International Student Administration Office on how to do this).\n\nFirst-cycle / single-cycle, open-access, requiring a TOLC: also upload the TOLC result certificate.\n\nFile formats: pdf/jpeg/png, max 10 MB. Then click \"Summary.\"",
  },
  {
    n: 6,
    title: "Summary & submit",
    body: "Review all data on the Summary page. Tick the privacy policy, then click \"Apply for pre-enrolment\" (the English interface labels it \"Submit prescription request\" — same button).\n\nBy submitting, the application goes to the University, which verifies it and forwards it, along with admission info, to the Consulate.\n\nThe signed declaration commits the student to: proving financial resources and health insurance coverage, applying for a residence permit within 8 working days of entry into Italy, and returning home if not admitted or enrolled.",
    warning: "Submission is binding. To change personal data after submission, contact Technical Support with a passport copy. To change the programme, contact the university directly.",
  },
  {
    n: 7,
    title: "Wait for validation",
    body: "On successful validation an automatic email arrives and the Universitaly summary can be downloaded. At this point validation is CONDITIONAL — it is subject to verification of the authenticity and value of the qualification.\n\nThe visa requires UNCONDITIONAL validation. See the Validation section below for requirements by programme type.",
  },
];

const VALIDATION_CATEGORIES = [
  {
    label: "Restricted-access programmes",
    color: "amber",
    items: [
      "Passed the admission test(s)",
      "Met the Italian language requirement (Italian-taught programmes only)",
      "Paid the first instalment of tuition fees",
      "Submitted the qualification supporting documents",
    ],
    note: null,
  },
  {
    label: "Open-access — First / Single-Cycle",
    color: "blue",
    items: [
      "Taken the required TOLC (or other required test)",
      "Met the Italian language requirement (Italian-taught programmes only)",
      "Submitted the qualification supporting documents",
      "Paid the first instalment of tuition fees",
    ],
    note: "If paying the first instalment is not yet possible, contact the International Student Administration Office to check whether it can still be validated unconditionally.",
  },
  {
    label: "Open-access — Second-Cycle",
    color: "purple",
    items: [
      "Passed the admission test(s)",
      "Met the Italian language requirement (Italian-taught programmes only)",
      "Submitted the qualification supporting documents",
      "Paid the first instalment of tuition fees",
    ],
    note: "If paying the first instalment is not yet possible, contact the International Student Administration Office to check whether it can still be validated unconditionally.",
  },
];

const FAQS: { q: string; a: string; bologna?: boolean }[] = [
  {
    q: "Do I pre-enrol or apply for admission first?",
    a: "Restricted-access programmes and open-access second-cycle: you may pre-enrol before the admission outcome, but admission is confirmed to the Consulate only after you have been accepted. Open-access first and single-cycle: you may pre-enrol before applying. Programmes with an admission test in Italy: you must pre-enrol before applying.",
  },
  {
    q: "What is the deadline for pre-enrolment?",
    a: "UNIBO sets no general deadline for pre-enrolment. Plan to get the visa in time to enrol and attend classes, and in any case before the Embassy's deadline. For programmes with restricted access at national level (Medicine, Veterinary), check the programme website for a specific deadline.",
    bologna: true,
  },
  {
    q: "Can I apply for two programmes? Do I pre-enrol twice?",
    a: "No — Universitaly allows only one pre-enrolment per university per academic year. Choose carefully. If not yet admitted, you can wait for results then pre-enrol. Alternatively, pre-enrol for one and request a change by writing to internationaldesk@unibo.it (waiting times vary). If admitted to more than one programme, choose which one to pre-register for.",
    bologna: true,
  },
  {
    q: "I haven't obtained my final qualification yet. What do I upload?",
    a: "For pre-enrolment — First-cycle: a certificate of enrolment in your final year of school and/or a provisional qualification. Second-cycle: a transcript of records and/or a provisional qualification. For the visa application: check with the relevant Consulate which documents are required. To complete enrolment later: upload the final qualification on Studenti Online using the dedicated procedure, then bring it to the Student Administration Office with documents proving its value and authenticity.",
  },
  {
    q: "Do I also have to upload a language certificate on Universitaly?",
    a: "No. However, if enrolling in an Italian-taught programme you must upload a valid Italian certificate to Studenti Online (or pass the Italian language test) to meet the language requirement. Warning: the Embassy/Consulate may require additional language certifications beyond those verified by the University.",
  },
  {
    q: "How long does verification take?",
    a: "A few days — or a few weeks during busy periods, for example in August.",
  },
  {
    q: "How do I obtain unconditional validation?",
    a: "See the Validation section on this page — requirements differ by programme type. For all programmes, the final in-person document check is done by the International Students Administration Office when the student completes enrolment. At UNIBO, notify the International Student Administration Office by email to initiate unconditional validation; they verify document authenticity and value, then validate.",
    bologna: true,
  },
  {
    q: "I want to change my programme within UNIBO — what do I do?",
    a: "Write to internationaldesk@unibo.it. Waiting times for changing pre-enrolment may vary. Note: if your pre-enrolment has already been validated, a change may require rejection — meaning you cannot submit further UNIBO pre-enrolments that academic year.",
    bologna: true,
  },
  {
    q: "I pre-enrolled at another university but now want UNIBO — what do I do?",
    a: "Ask the other university to reopen or reject your pre-enrolment application. Once reopened or rejected, submit a new pre-enrolment application for the UNIBO degree programme.",
  },
  {
    q: "I pre-enrolled at UNIBO but now want another university — what do I do?",
    a: "Write to internationaldesk@unibo.it to request reopening of your pre-enrolment. If already validated, UNIBO will have to reject it — you will not be able to submit further UNIBO pre-enrolments that academic year. Important: pre-enrolment cannot be reopened or rejected once the Consulate has entered the visa outcome (\"Visa issued\" or \"Visa denied\").",
    bologna: true,
  },
  {
    q: "Which office do I contact for pre-enrolment clarifications?",
    a: "At UNIBO — Italian programmes and Medicine & Surgery: internationaldesk@unibo.it. English programmes: the programme coordinator or programme tutor (email on the degree programme website, in the Contacts section). For other universities, substitute the equivalent international office.",
    bologna: true,
  },
  {
    q: "My English programme shows \"Italian/English\" on Universitaly — can I correct it?",
    a: "No. The pre-enrolment form indicates Italian as the language of instruction when the degree programme is formally Italian-taught, even if there are curricula with different teaching languages. This setting is auto-generated and cannot be modified.",
  },
];

const BOLOGNA_CHEAT = [
  { field: "Institution Name", value: "Università degli Studi di Bologna" },
  { field: "ID account (Step B)", value: "@studio.unibo.it (register on Studenti Online first)" },
  { field: "Clarifications — Italian programmes & Medicine & Surgery", value: "internationaldesk@unibo.it" },
  { field: "Clarifications — English programmes", value: "Programme coordinator / tutor (on programme website → Contacts)" },
  { field: "Change pre-enrolment / reopen", value: "internationaldesk@unibo.it" },
  { field: "Admission letter for visa", value: "NOT issued by UNIBO — use the Universitaly validated summary" },
];

// ─── Sub-components ──────────────────────────────────────────────────────────

function StepCard({ n, title, body, warning, bologna }: {
  n: number; title: string; body: string; warning?: string; bologna?: boolean;
}) {
  return (
    <div className="flex gap-4">
      <div className="flex-shrink-0 w-8 h-8 rounded-full bg-indigo-600 text-white text-sm font-bold flex items-center justify-center mt-0.5">
        {n}
      </div>
      <div className="flex-1 pb-6 border-b border-gray-100 last:border-0">
        <div className="flex items-center gap-2 mb-1.5">
          <p className="text-sm font-bold text-gray-900">{title}</p>
          {bologna && (
            <span className="text-[10px] font-bold bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded">🔵 BOLOGNA</span>
          )}
        </div>
        <p className="text-xs text-gray-600 leading-relaxed whitespace-pre-line">{body}</p>
        {warning && (
          <div className="mt-2.5 flex items-start gap-2 bg-amber-50 border border-amber-200 rounded-md px-3 py-2">
            <AlertTriangle className="w-3.5 h-3.5 text-amber-600 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-amber-800 leading-relaxed">{warning}</p>
          </div>
        )}
      </div>
    </div>
  );
}

function FaqItem({ q, a, bologna }: { q: string; a: string; bologna?: boolean }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-gray-100 last:border-0">
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-start justify-between gap-3 py-3.5 text-left hover:bg-gray-50 px-1 -mx-1 rounded transition-colors"
      >
        <span className="text-sm font-medium text-gray-800 leading-snug">{q}</span>
        <ChevronDown className={`w-4 h-4 text-gray-400 flex-shrink-0 mt-0.5 transition-transform duration-150 ${open ? "rotate-180" : ""}`} />
      </button>
      {open && (
        <div className="pb-4 px-1 space-y-1.5">
          <p className="text-xs text-gray-600 leading-relaxed">{a}</p>
          {bologna && (
            <p className="text-[10px] text-blue-600 font-medium">🔵 Bologna-specific detail</p>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Page ────────────────────────────────────────────────────────────────────

export default function Universitaly() {
  const [validationTab, setValidationTab] = useState(0);

  return (
    <div className="min-h-screen bg-[#F8F9FC]">

      {/* Header */}
      <div className="bg-[#0B1A33] text-white py-8">
        <div className="max-w-4xl mx-auto px-4">
          <div className="flex items-center gap-3 mb-2">
            <Globe className="w-6 h-6 text-blue-400" />
            <h1 className="text-2xl font-bold" style={{ fontFamily: "Playfair Display, serif" }}>
              Universitaly — Pre-enrolment Guide
            </h1>
          </div>
          <p className="text-blue-300 text-sm">
            How to pre-enrol on Universitaly for a study visa — applicable to every Italian university.
          </p>
          <a
            href="https://www.universitaly.it"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 mt-3 text-xs text-blue-400 hover:text-white transition-colors"
          >
            <ExternalLink className="w-3.5 h-3.5" />
            www.universitaly.it
          </a>
        </div>
      </div>

      {/* Source banner */}
      <div className="bg-amber-50 border-b border-amber-200">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-start gap-2">
          <Info className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
          <p className="text-amber-800 text-xs leading-relaxed">
            Built from UNIBO's "Guide to pre-enrolment on Universitaly and FAQs" (updated 16 June 2026).
            The portal steps are identical for any Italian university. Items tagged <span className="font-bold text-blue-700">🔵 BOLOGNA</span> are UNIBO-specific — substitute the equivalent institution name, student-portal account, and international office for other destinations.
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 space-y-10">

        {/* Golden rules */}
        <div className="bg-indigo-600 rounded-xl text-white p-5">
          <div className="flex items-center gap-2 mb-3">
            <BookOpen className="w-4 h-4" />
            <p className="text-sm font-bold uppercase tracking-wide">Two golden rules — state these to every client</p>
          </div>
          <div className="space-y-2">
            <div className="flex items-start gap-2.5">
              <span className="w-5 h-5 rounded-full bg-white/20 text-white text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">1</span>
              <p className="text-sm"><strong>Pre-enrolment is REQUIRED</strong> to apply for a study visa.</p>
            </div>
            <div className="flex items-start gap-2.5">
              <span className="w-5 h-5 rounded-full bg-white/20 text-white text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">2</span>
              <p className="text-sm"><strong>Pre-enrolment does NOT guarantee admission</strong> — the student must also complete the university's specific admission procedure (application / test / ranking).</p>
            </div>
          </div>
        </div>

        {/* Critical rules */}
        <section>
          <h2 className="text-base font-bold text-gray-900 mb-3 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-red-500" />
            Critical rules — what causes problems
          </h2>
          <div className="space-y-2.5">
            {CRITICAL_RULES.map((r, i) => (
              <div key={i} className={`rounded-lg border px-4 py-3 ${r.bologna ? "border-blue-200 bg-blue-50" : "border-red-100 bg-red-50"}`}>
                <div className="flex items-center gap-2 mb-0.5">
                  <p className={`text-xs font-bold ${r.bologna ? "text-blue-800" : "text-red-800"}`}>{r.rule}</p>
                  {r.bologna && <span className="text-[10px] font-bold bg-blue-200 text-blue-700 px-1.5 py-0.5 rounded">🔵 BOLOGNA</span>}
                </div>
                <p className={`text-xs leading-relaxed ${r.bologna ? "text-blue-700" : "text-red-700"}`}>{r.detail}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Step-by-step */}
        <section>
          <h2 className="text-base font-bold text-gray-900 mb-5 border-b border-gray-200 pb-2">
            Step-by-step walkthrough
          </h2>
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm px-5 py-4">
            {STEPS.map(s => (
              <StepCard key={s.n} {...s} />
            ))}
          </div>
        </section>

        {/* Validation */}
        <section>
          <h2 className="text-base font-bold text-gray-900 mb-1 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
            Validation: Conditional → Unconditional
          </h2>
          <p className="text-xs text-gray-500 mb-4">The visa requires <strong className="text-gray-700">UNCONDITIONAL</strong> validation. Requirements differ by programme type.</p>

          {/* Tab switcher */}
          <div className="flex gap-1 p-1 bg-gray-100 rounded-lg mb-4 w-fit">
            {VALIDATION_CATEGORIES.map((cat, i) => (
              <button
                key={i}
                onClick={() => setValidationTab(i)}
                className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                  validationTab === i ? "bg-white text-gray-900 shadow-sm" : "text-gray-500 hover:text-gray-700"
                }`}
              >
                {cat.label}
              </button>
            ))}
          </div>

          {VALIDATION_CATEGORIES.map((cat, i) => (
            validationTab !== i ? null : (
              <div key={i} className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
                <div className="bg-gray-50 px-5 py-3 border-b border-gray-200">
                  <p className="text-xs font-bold text-gray-700">To obtain unconditional validation — {cat.label}</p>
                </div>
                <ul className="px-5 py-4 space-y-2.5">
                  {cat.items.map((item, j) => (
                    <li key={j} className="flex items-start gap-2.5">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 flex-shrink-0 mt-0.5" />
                      <p className="text-sm text-gray-700 leading-relaxed">{item}</p>
                    </li>
                  ))}
                </ul>
                {cat.note && (
                  <div className="mx-5 mb-4 flex items-start gap-2 bg-blue-50 border border-blue-200 rounded-md px-3 py-2">
                    <Info className="w-3.5 h-3.5 text-blue-600 flex-shrink-0 mt-0.5" />
                    <p className="text-xs text-blue-800 leading-relaxed">{cat.note}</p>
                  </div>
                )}
              </div>
            )
          ))}

          <div className="mt-3 bg-indigo-50 border border-indigo-200 rounded-lg px-4 py-3">
            <p className="text-xs text-indigo-800 leading-relaxed">
              <strong>For all programmes:</strong> the final, in-person document verification is done by the International Students Administration Office when the student completes enrolment.
              🔵 At UNIBO, email the International Student Administration Office to initiate unconditional validation — they verify document authenticity and value, then validate.
            </p>
          </div>
        </section>

        {/* FAQ */}
        <section>
          <h2 className="text-base font-bold text-gray-900 mb-1">FAQ highlights</h2>
          <p className="text-xs text-gray-500 mb-4">What agents get asked most. Items tagged 🔵 include Bologna-specific detail.</p>
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm px-5">
            {FAQS.map((f, i) => (
              <FaqItem key={i} q={f.q} a={f.a} bologna={f.bologna} />
            ))}
          </div>
        </section>

        {/* Bologna cheat sheet */}
        <section>
          <h2 className="text-base font-bold text-gray-900 mb-1">
            🔵 Bologna-specific quick reference
          </h2>
          <p className="text-xs text-gray-500 mb-4">Values to use when filling in Universitaly for a UNIBO programme. Replace with the equivalent for other destinations.</p>
          <div className="bg-white rounded-xl border border-blue-200 shadow-sm overflow-hidden">
            <div className="bg-blue-600 px-5 py-2.5">
              <p className="text-xs font-bold text-white">Università di Bologna — Universitaly field values</p>
            </div>
            <table className="w-full">
              <tbody className="divide-y divide-gray-100">
                {BOLOGNA_CHEAT.map((row, i) => (
                  <tr key={i} className="hover:bg-gray-50">
                    <td className="px-5 py-3 text-xs font-semibold text-gray-600 w-64 align-top">{row.field}</td>
                    <td className="px-5 py-3 text-xs text-gray-800 leading-relaxed">{row.value}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

      </div>
    </div>
  );
}
